// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpgzkripstgsoclqzdym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwZ3prcmlwc3Rnc29jbHF6ZHltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTMwMTIsImV4cCI6MjA2MDk4OTAxMn0.Z8trMv84ZRgxJVekZMVvi1qDmv0sjsOwcieQsf0x694";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);